### ISSUE TITLE
Display does not work properly

### ISSUE THREAD

**Issue by fhwedel-hoe** [fhwedel-hoe/OpenRoadEd#3]
Due to the changes in [OSGMain.cpp](https://github.com/fhwedel-hoe/OpenRoadEd/blob/084f730163de6abcc236599e2bff6dec50ed802b/OpenRoadEd/Osg/OSGMain.cpp#L209), the OpenSceneGraph is no longer attached to the Qt Widget it is supposed to be drawn on. This was previously implemented in a Windows-only way. This needs to be re-done in a proper manner, such as [the example](https://github.com/openscenegraph/osgQt/blob/master/examples/osgviewerQt/osgviewerQt.cpp) shows.

* The positioning is off.
* The OpenSceneGraph view can fall behind the Qt Window.
* Scaling somehow affects the content.
* The view seems unresponsive to mouse events.
* The designated UI space does not update (showing the last displayed screen content).

![screenshot](https://raw.githubusercontent.com/fhwedel-hoe/OpenRoadEd/master/Screenshots/display-issues.png)

I have no experience with Qt or OpenSceneGraph whatsoever. Any help on this is appreciated.

**Comment by karolmateusznowak** [comment]
You could replace Qt with imgui

**Comment by fhwedel-hoe** [comment]
@karolmateusznowak Switching to imgui would be an extensive change. Sticking to Qt is easier. I expect someone who knows how to integrate OpenSceneGraph into a Qt widget, this is an easy fix.

**Comment by ebadi** [comment]
@fhwedel-hoe Qt 4.8.7 is discontinued on December 2015 and many linux distros moved to Qt5 and therefore I thought it is good idea to port OpenRoadEd to [Qt 5](https://github.com/ebadi/OpenRoadEd) to be able to get support from Qt community as well. 
 
![image](https://user-images.githubusercontent.com/1111940/103387859-56053180-4b06-11eb-82f1-96aecda16c70.png)

With this said, is it possible for you to give me more hints what has to be done to fix these issues? What has been done correctly in the example you [mentioned](https://github.com/openscenegraph/osgQt/blob/master/examples/osgviewerQt/osgviewerQt.cpp) that is missing in the current implementation.

**Comment by fhwedel-hoe** [comment]
Yes, your branch works. With "works" as in "not more broken than it has been before". ;)
![grafik](https://user-images.githubusercontent.com/33323898/103420206-741a7280-4b96-11eb-86ae-c37b7e2fe04f.png)

Please note I merely forked the repository, noticed the display is not working out of the box and then decided to leave it to someone else, as I have no experience with Qt or OpenSceneGraph. 

In the original, there is this line `traits->inheritedWindowData = new WindowData(window);` which – as far as I understand – reads the information from `window` and tells OpenSceneGraph "this is the window you should use to display yourself on". Unfortunately, this feature seems to be Windows only (`window` is a win32 handle). :( I could not make heads or tails of the platform-independent [example](https://github.com/openscenegraph/osgQt/blob/master/examples/osgviewerQt/osgviewerQt.cpp). It seems to use a completely different approach which "just works".

**Comment by ebadi** [comment]
> The icons are not compiled in, but rather read from the working directory. The working directory must contain the "Resources" folder.

Thanks for this hint and testing my work. It seems that you loaded the same open drive file with the version that I am working on. I actually cannot open any of my opendrive files. 

> Please note I merely forked the repository, noticed the display is not working out of the box and then decided to leave it to someone else, as I have no experience with Qt or OpenSceneGraph.

Me neither but I would like to give it a try. Thanks for the pointer. 

I guess I need to convert `#include <osgViewer/api/Win32/GraphicsWindowWin32>` to `#include <osgViewer/api/X11/GraphicsWindowX11>` or `<osgViewer/api/Win32/GraphicsWindow>`  and move forward. 

I found that someone has already done something similar before  [here](http://interreality.org/bzroot/vos/s5.3/src/app/threedeeqt/QOSGWidget.cpp). I will try to see if we can use it when I find some time.

**Comment by fhwedel-hoe** [comment]
> Thanks for this hint and testing my work. It seems that you loaded the same open drive file with the version that I am working on. I actually cannot open any of my opendrive files.

You are right, I opened the file in the github repo. Like many others these days, I am working from home a lot and do not have other files at hand. From the top of my head, I remember that OpenRoadEd supports only one kind of turns (either polyline or arc), but not the other one, which happens to be popular. Due to the issue with the display, I never even tried to expand OpenRoadEd's support for turns.

> I found that someone has already done something similar (…).

Using `winId()` sounds promising. I did not even know that existed. :D

**Comment by ebadi** [comment]
Hi,
WinId was actually the solution. :) 
Do you prefer that I send a pull request fixing this issue separately or do you want me to send a giant pull rquest with QT5 port + the fix all together? 
I am planning to cleaup the documentation and the build script next. Would it be possible for you to close this issue, go through the issue list above and create a separate for those issues that are critical?

**Comment by fhwedel-hoe** [comment]
Nice work, very good!

<img src="https://media1.tenor.com/images/b4ea018aeaf23727b9a7f6bc43ef9a46/tenor.gif">

I merged your commits, did some tests and adjusted the code to for compatibility on Windows. The display is now working better, although not perfect. Mouse navigation does not seem to work at all, but that is as good as it gets for now, I guess. :)

**Comment by ebadi** [comment]
I fixed few minor issues in the documentation and send the pull request https://github.com/fhwedel-hoe/OpenRoadEd/pull/7

> This can be skipped if osgQt in your system is reasonably recent.

Interesting! How did you install osgQt and what version are you at?  As far as I remember, when I get the prepackaged software via apt-get, there were several files ( in /usr/lib or /usr/include) that were missing. I therefore build an older version of the osgQt, (hence `git checkout 6e4de`) . Would be nice to double check this and possibly remove this extra step from the instruction.

**Comment by fhwedel-hoe** [comment]
@ebadi On Ubuntu 18.04, I ran `apt-get install libopenscenegraph-dev`. It installed version 3.2.3 which just worked out of the box. On Windows, I used vcpkg which builds version 3.6.5.

Note: In 324a7d5, I replaced `pkg_check_modules(OSG REQUIRED openscenegraph)` by `find_package(OpenSceneGraph…)`. Maybe the pgk-config files supplied by openscenegraph are no longer maintained?

**Comment by ebadi** [comment]
@fhwedel-hoe  On ubuntu 20.04 `apt-get install libopenscenegraph-dev` results in Version: 3.6.4+dfsg1-3build2 to be installed (which is very similar to the version that you use for building on Windows!!!) but I get the following error on build: 
```
...
[ 38%] Building CXX object CMakeFiles/OpenRoadEd.dir/Osg/OSGMain.cpp.o
/home/test/OpenRoadEd/OpenRoadEd/Osg/OSGMain.cpp:15:10: fatal error: osgQt/GraphicsWindowQt: No such file or directory
   15 | #include <osgQt/GraphicsWindowQt>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/OpenRoadEd.dir/build.make:349: CMakeFiles/OpenRoadEd.dir/Osg/OSGMain.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:77: CMakeFiles/OpenRoadEd.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
I tried to put back the line that you replaced but nothing changed.
```
find_package(PkgConfig)	
pkg_check_modules(OSG REQUIRED openscenegraph)
```

So the newer versions of libopenscenegraph-dev breaks the build instruction and therefore we need to downgrade to an older version of osgQt. I updated the readme file here:  https://github.com/fhwedel-hoe/OpenRoadEd/pull/11

Another solution is to install an older version of libopenscenegraph-dev with apt-get but I don't recommend it as this sometimes break dependencies.

**Comment by fhwedel-hoe** [comment]
Indeed. It looks like Ubuntu 20.04 "focal" and Debian 11 "Bullseye" do not include osgQt in their openscenegraph packages.
