### ISSUE TITLE
compile on ubuntu

### ISSUE THREAD

**Issue by HelloJK** [fhwedel-hoe/OpenRoadEd#5]
can you compile this project on ubuntu? 
if so, can you give me some me some advice for this?

**Comment by HelloJK** [comment]
as this project is a visual studio project, so i don't know how to construct this project in qt and linux platform

**Comment by fhwedel-hoe** [comment]
This is not only a "Visual Studio Project", but also supports cmake and Qt Creator. Simply open [`OpenRoadEd/OpenRoadEd.pro`](https://github.com/fhwedel-hoe/OpenRoadEd/blob/master/OpenRoadEd/OpenRoadEd.pro) in Qt Creator. Or invoke cmake so it uses `OpenRoadEd/CMakeLists.txt`.
