### ISSUE TITLE
Error in Opendrive file (.xodr) handling 

### ISSUE THREAD

**Issue by ebadi** [fhwedel-hoe/OpenRoadEd#8]
As it is already known, even the sample opendrive file cannot be opened by tools correctly. 
![image](https://user-images.githubusercontent.com/1111940/103903543-50a67900-50fc-11eb-939d-b9d00e8eec1e.png)
After a few hours of debugging I noticed that the road file that is opened by OpenRoadEd doesn't look like the same as the road that is saved by the same version of the OpenRoadEd and I suspect that it has either sth to do with loading or saving these files since the values for many parameters are not identical in these two states. 

Road shape that is created by OpenRoadEd:
![x1](https://user-images.githubusercontent.com/1111940/103904078-14274d00-50fd-11eb-8cb1-53c4077afe15.png)

The resulting OpenDrive file saved on disk
[test.txt](https://github.com/fhwedel-hoe/OpenRoadEd/files/5782127/test.txt)

The opendrive that is loaded by OpenRoadEd:
![x2](https://user-images.githubusercontent.com/1111940/103904086-1689a700-50fd-11eb-91fb-23b3120562d8.png)

**Comment by fhwedel-hoe** [comment]
When you brought up this issue, I looked at the values and noticed all decimal information was missing. "locale" popped into my mind. When setting locale to the C fallback explicitly, it works on my system:

    cd ~/OpenRoadEd
    LC_ALL=C OpenRoadEd/build/OpenRoadEd

**Comment by ebadi** [comment]
Great, another issue is now fixed. :)
