### ISSUE TITLE
Selection of items in 3D view area is not possible

### ISSUE THREAD

**Issue by ebadi** [fhwedel-hoe/OpenRoadEd#9]
Using Windows pre-compiled binary, it is possible to select an element in 3D view area to see its properties, however on Linux, clicking and selecting an item is not possible. 

I suspect that the issue has something to do with the [CameraManipulator class](https://github.com/ebadi/OpenRoadEd/blob/master/OpenRoadEd/Osg/OSGCameraControls2.cpp).

To Check: Whether the version compiled on Windows with Qt5 behaves correctly.

**Comment by fhwedel-hoe** [comment]
I just compiled on Windows. Same behavior. Not ideal, but at least it is consistent across platforms. :)

As 3D navigation also does not work, I suspect mouse events are not forwarded to the OSG component at all.

**Comment by ebadi** [comment]
I am now debugging [this part of the cod](https://github.com/ebadi/OpenRoadEd/blob/master/OpenRoadEd/Qt/QOSGWidget.cpp#L282). It seems that `mOsgMain->PickNode` never returns a valid node.

**Comment by ebadi** [comment]
I spent a little bit more on this today. It seems that `mViewer->computeIntersections(x,y,intersections)` in `OSGMain::PickNode` returns no node. [In this line](https://github.com/fhwedel-hoe/OpenRoadEd/blob/master/OpenRoadEd/Osg/OSGMain.cpp#L811) we have valid mouse coordinates (x,y) but the function returns false eventhough there are nodes (either after loading the sample .xodr file or after drawing a basic road). 
```
 computeIntersections

public boolean computeIntersections(float x,
                                    float y,
                                    INTERSECTVISITORHitList hits)

    compute, from normalized mouse coords, for all Cameras, intersections with the scene. parameters:

    Parameters:
        x - float
        y - float
        hits - openscenegraph.osgUtil.INTERSECTVISITORHitList
```

**Comment by ebadi** [comment]
Ok, now I got access to a Windows machine and I see that the OpenRoadEd's Windows binary acts exactly the same as our version of OpenRoadEd. In the tree view, you can select a node and its corresponding object changes its color (as shown below). When you click on an object in 3D view nothing changes in the tree view which is consistent across platforms.
![image](https://user-images.githubusercontent.com/1111940/104187675-71cada80-5418-11eb-91e0-c541d294ff68.png)
